title: Asciidoctor
description: An open source implementation of AsciiDoc in Ruby
author: Asciidoctor Project
blog_path: /news
# Disable interpolate after upgrading to Awestruct 0.5.4
#interpolate: false
# FIXME timezone will need to be specified per post for a global team
local_tz: America/Denver
disqus: asciidoctor
disqus_generate_id: true
disqus_developer: true
haml:
  :ugly: true
asciidoctor:
  :safe: unsafe
  :base_dir: null
  :attributes:
    # TODO Awestruct should set env-awestruct
    #env-awestruct: ''
    compat-mode: '@'
    attribute-missing: warn
    relfileprefix: '../'
    outfilesuffix: '/'
    idprefix: ''
    idseparator: '-'
    icons: font
    sectanchors: ''
    linkattrs: ''
    #source-highlighter: highlight.js
    source-highlighter: coderay
    prewrap: null
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: nil
    #show_drafts: false
  staging:
    deploy: nil
  production:
    base_url: http://asciidoctor.org
    disqus_developer: false
    # long-hand form for Asciidoctor
    google_analytics_account: UA-38215684-1
    google_analytics:
      account: UA-38215684-1
    scss:
      :line_numbers: false
      :style: :compressed
    #compass_output_style: compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy:
      host: github_pages
      branch: gh-pages
