CREATE TABLE "GONGANYUN2"."ES_COLUMN"
(
"PROPERTY_ID" VARCHAR(64) NOT NULL,
"TID" VARCHAR(64),
"COLUMN_ID" VARCHAR(64),
"COLUMN_NAME" VARCHAR(50),
"COLUMN_COMMENT" VARCHAR(50) DEFAULT 1,
"COLUMN_LABEL" VARCHAR(50),
"DICTIONARY_ID" VARCHAR(50),
"DATA_TYPE" VARCHAR(50),
"LENGTH" VARCHAR(50),
"DATA_FORMAT" VARCHAR(50),
"DISPLAY_FORMAT" VARCHAR(50),
"INDEX_TYPE" INTEGER,
"INDEX_ANALYZER" VARCHAR(50),
"SEARCH_ANALYZER" VARCHAR(50),
"SORT_NUM" INTEGER,
"CREATE_TIME" TIMESTAMP(6),
"CREATE_USER" VARCHAR(64),
"UPDATE_TIME" TIMESTAMP(6),
"UPDATE_USER" VARCHAR(64),
"MEMO1" VARCHAR(50),
"MEMO2" VARCHAR(50),
"BOOST" INTEGER DEFAULT 1,
NOT CLUSTER PRIMARY KEY("PROPERTY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "GONGANYUN2"."ES_COLUMN" IS '索引列表';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."PROPERTY_ID" IS '主键ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."TID" IS '索引表ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."COLUMN_ID" IS '元数据列ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."DATA_FORMAT" IS '日期列格式';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."INDEX_TYPE" IS '索引类型，0不索引，1分词索引，2不分词直接索引';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."INDEX_ANALYZER" IS '索引分词器，如ik';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."SEARCH_ANALYZER" IS '搜索分词器，如ik';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."CREATE_USER" IS '创建用户';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."UPDATE_USER" IS '更新用户';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."MEMO1" IS '备用字段1';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."MEMO2" IS '备用字段2';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."DATA_TYPE" IS '列数据类型';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."SORT_NUM" IS '排序号';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."COLUMN_NAME" IS '列名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."COLUMN_COMMENT" IS '列注释';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."COLUMN_LABEL" IS '列标签';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."LENGTH" IS '列长度';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."DISPLAY_FORMAT" IS '日期列显示格式';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."DICTIONARY_ID" IS '字典列';
COMMENT ON COLUMN "GONGANYUN2"."ES_COLUMN"."BOOST" IS '权重值';

CREATE TABLE "GONGANYUN2"."ES_INDEX_SQL"
(
"ID" VARCHAR(50),
"TID" VARCHAR(50),
"DATASET_ID" VARCHAR(50),
"CREATE_SQL" VARCHAR(500),
"ADD_SQL" VARCHAR(500),
"UPDATE_SQL" VARCHAR(500)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_SQL"."ID" IS '主键ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_SQL"."TID" IS '索引表ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_SQL"."DATASET_ID" IS '数据集ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_SQL"."CREATE_SQL" IS '创建索引SQL';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_SQL"."ADD_SQL" IS '增量追加索引SQL';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_SQL"."UPDATE_SQL" IS '更新修改索引SQL';

CREATE TABLE "GONGANYUN2"."ES_INDEX_TABLE"
(
"TID" VARCHAR(64) NOT NULL,
"TABLE_NAME" VARCHAR(128),
"ALIASES" VARCHAR(128),
"DATASET_ID" VARCHAR(256),
"NODE_ID" VARCHAR(50),
"UPDATE_TYPE" INT,
"ALL_NUM" NUMBER(32,6),
"ADD_NUM" NUMBER(32,6),
"UPDATE_NUM" NUMBER(32,6),
"USER_NAME" VARCHAR(50),
"CREATE_TIME" TIMESTAMP(6),
"LAST_ADD_TIME" TIMESTAMP(6),
"LAST_UPDATE_TIME" TIMESTAMP(6),
"INDEX_NAME" VARCHAR(128),
"TYPE_NAME" VARCHAR(50),
"STATUS" INT,
"LAST_STATUS" INT,
"UPDATE_NAME" VARCHAR(50),
"NOTE" VARCHAR(50),
"MAPPING" VARCHAR2(4000),
"INSERT_HANDLER" VARCHAR2(50),
"SORT_NUM" INTEGER,
NOT CLUSTER PRIMARY KEY("TID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."TID" IS '索引表ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."TABLE_NAME" IS '索引表名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."ALL_NUM" IS '数据总量';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."ADD_NUM" IS '追加数据量';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."UPDATE_NUM" IS '更新数据量';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."NODE_ID" IS '节点id';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."LAST_ADD_TIME" IS '最后追加时间';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."INDEX_NAME" IS '索引名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."TYPE_NAME" IS '类型名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."ALIASES" IS '别名';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."DATASET_ID" IS '数据集ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."UPDATE_TYPE" IS '更新类型';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."USER_NAME" IS '创建用户';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."STATUS" IS '索引表状态';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."LAST_STATUS" IS '索引表上一状态';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."UPDATE_NAME" IS '更新时间';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."MAPPING" IS '索引mapping';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."INSERT_HANDLER" IS '插入索引Handler';
COMMENT ON COLUMN "GONGANYUN2"."ES_INDEX_TABLE"."SORT_NUM" IS '排序号';

CREATE TABLE "GONGANYUN2"."ES_NODE"
(
"NODE_ID" VARCHAR(50) NOT NULL,
"NODE_NAME" VARCHAR(64),
"NODE_IP" VARCHAR2(1024),
"STATUS" INT,
"CLUSTER_NAME" VARCHAR(50),
"IS_CLUSTER_NODE" INT,
"LAST_UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("NODE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."NODE_ID" IS '节点id';
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."NODE_NAME" IS '节点名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."STATUS" IS '节点状态,1,2,3';
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."CLUSTER_NAME" IS '集群名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."NODE_IP" IS '节点ip，如10.75.0.1:9300,10.75.0.2:9301';
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."IS_CLUSTER_NODE" IS '是否集群节点';
COMMENT ON COLUMN "GONGANYUN2"."ES_NODE"."LAST_UPDATE_TIME" IS '最后修时间';

CREATE TABLE "GONGANYUN2"."ES_PROPERTY"
(
"ID" VARCHAR(64) NOT NULL,
"PROPERTY_CODE" VARCHAR(64),
"PROPERTY_NAME" VARCHAR(64),
"NOTE" VARCHAR(128),
"MEMO1" VARCHAR(128),
"MEMO2" VARCHAR(128),
"UPDATE_USER" VARCHAR(64),
"UPDATE_TIME" TIMESTAMP(6),
CONSTRAINT "PK_ES_PROPERTY" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "GONGANYUN2"."ES_PROPERTY" IS '数据属性';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."ID" IS '属性ID';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."PROPERTY_CODE" IS '属性代码';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."PROPERTY_NAME" IS '属性名称';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."NOTE" IS '备注';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."MEMO1" IS '备用字段1';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."MEMO2" IS '备用字段2';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."UPDATE_USER" IS '最近更新人';
COMMENT ON COLUMN "GONGANYUN2"."ES_PROPERTY"."UPDATE_TIME" IS '最近更新时间';

CREATE TABLE "GONGANYUN2"."ES_PROPERTY_COLUMN_MAPPING"
(
"MAPPING_ID" VARCHAR(64) NOT NULL,
"ES_COLUMN_ID" VARCHAR(64),
"CODE" VARCHAR(50),
CONSTRAINT "PK_ES_PROPERTY_COLUMN_MAPPING" NOT CLUSTER PRIMARY KEY("MAPPING_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;